name: Publish to Pypi

on: [push]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Build package
      run: make build
    - name: Archive artefact
      uses: actions/upload-artifact@v3
      with:
        name: wheel
        path: dist/*.whl
#    - name: Publish to Pypi
#      uses: pypa/gh-action-pypi-publish@release/v1
#      with:
#        password: ${{ secrets.PYPI_TOKEN }}

